exporters:
    debug: {}
processors: {}
receivers:
    otlp:
        protocols:
            grpc: {}
            http: {}
service:
    pipelines:
        logs/default:
            exporters:
                - debug
            processors: []
            receivers:
                - otlp
    telemetry:
        metrics:
            level: detailed
            readers:
                - pull:
                    exporter:
                        prometheus:
                            host: 0.0.0.0
                            port: 8888
