name: Build & Release Agent

on:
  push:
    tags:
      - 'agent/v*'  # tag like agent/v0.1.0 to trigger

defaults:
  run:
    working-directory: agent

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build binary
        run: |
          mkdir -p dist/
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/ctrlb_collector-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/ctrlb_collector

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ctrlb-collector-binaries
          path: agent/dist/

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: agent
          file: agent/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ctrlb-agent:${{ github.ref_name }}
        
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: ctrlb-collector-binaries
          path: agent/dist/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: agent/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
